---
- name: Collect instance info
  os_server_info:
  register: instances

- name: Build in-Memory inventory
  add_host:
    host: "{{ instance.name }}"
    group: "{{ instance.group}}"
  when: instance.meta.deployment_name == instance_settings.deployment_name
  loop: "{{ instances.openstack_servers }}"
  loop_control:
    loop_var: instance

- name: Print current hosts
  debug: var=groups
