---
- name: Collect instance info
  os_server_info:
  register: instances

- name: Build in-Memory inventory
  add_host:
    host: "{{ instance.name }}"
    group: "{{ multitierinfra.AnsibleGroup }}"
  when: instance.metadata.AnsibleGroup == "{{ multitierinfra.AnsibleGroup }}"
  loop: "{{ instances.openstack_servers }}"
  loop_control:
    loop_var: instance

- name: Print current hosts
  debug: var=groups
