---
- name: Build In-Memory Inventory
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Collection instance info
      os_server_info:
        cloud: "{{ guid }}-project"
      register: instances

    - name: Build In-Memory inventory
      add_host:
        host: "{{ instance.name }}"
        group: "{{ instance.metadata.AnsibleGroup }}"
      when: instance.metadata.AnsibleGroup == {{ AnsibleGroup }}
      loop: "{{ instances.openstack_servers }}"
      loop_control:
        loop_var: instance

- name: Print current hosts
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - debug: var=groups
