---
- name: Collect instance info
  os_server_info:
  register: os_instances

- name: Build in-Memory inventory
  add_host:
    host: "{{ instance.name }}"
    group: "{{ instance.metadata.AnsibleGroup}}"
  when: instance.metadata.deploymentname ==  instance_settings.deployment_name
  loop: "{{ os_instances.openstack_servers }}"
  loop_control:
    loop_var: instance

- name: Print current hosts
  debug: var=groups
