---
- name: Collection instance info
  os_server_info:
  register: instances

- name: Build In-Memory inventory
  add_host:
    host: "{{ instance.name }}"
    group: "{{ instance.metadata.AnsibleGroup }}"
  when: instance.metadata.AnsibleGroup == {{ AnsibleGroup }}
  loop: "{{ instances.openstack_servers }}"
  loop_control:
    loop_var: instance

- name: Print current hosts
  debug: var=groups
