- import_playbook: build-in-memory-inventory.yml

- name: Deploy, configure, and populate Postgres 12
  hosts: database_servers
  become: true
  gather_facts: false

  tags:
    - database_servers

  roles:
    - role: deploy-postgres12-role

