---
- name: Create infrastructure for multi-tier application in OpenStack
  hosts: localhost
  connection: local

  roles:
    - role: create-instance
      vars:
        guid: 3365
        instances:
          - name: frontend1
            flavor: "GLOBAL-CPU_4_Memory_8192_Disk_30_flavor"
            keypair: "{{ guid }}-keypair"
            security_group: "{{ guid }}-HostSG"
            internal_network: "{{ guid }}-dev-network"
            metadata:
              AnsibleGroup: osp_instances_lab
              deployment_name: dev
  vars:
    multitierinfra:
      image: rhel-8.3

