---
- name: Play to setup infrastructure on OpenStack 
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - role: create-instances
      vars:
        guid: "{{ lookup('ENV','GUID') }}"
