---
- name: Create infrastructure for multi-tier application in OpenStack
  hosts: localhost
  connection: local

  vars:
    guid: 3365
    instance_settings:
      image: rhel-8.3
      flavor: "GLOBAL-CPU_4_Memory_8192_Disk_30_flavor"
      keypair: "{{ guid }}-keypair"
      security_group: "{{ guid }}-HostSG"
      internal_network: "{{ guid }}-dev-network"
      deployment_name: "dev"

  roles:
    - role: create-instance-role
      vars:
        instances:
          - name: frontend1
            group: load_balancers
         # - name: app1
         #  group: app_servers,dev
         #- name: app2
         #   group: app_servers,dev
         # - name: appdb1
         #   group: database_servers

    - role: build-in-memory-inventory-role
        
- name: check if host is there
  hosts: all
  tasks:
    - ping:

#    - role: configure-instance-role


