---
- name: Create infrastructure for multi-tier application in OpenStack
  hosts: localhost
  connection: local

  roles:
    - role: create-instance
      vars:
        instances:
          - name: frontend1
            metadata:
              deployment_name: frontend
              AnsibleGroup: mitzicom_multitier_frontends
          - name: app1
            metadata:
              deployment_name: app1
              AnsibleGroup: mitzicom_multitier_apps
          - name: app2
            metadata:
              deployment_name: app2
              AnsibleGroup: mitzicom_multitier_apps
          - name: appdb1
            metadata:
              deployment_name: appdb1
              AnsibleGroup: mitzicom_multitier_appdbs
  vars:
    guid: 3365
    multitierinfra:
      image: rhel-8.3
      flavor: "GLOBAL-CPU_4_Memory_8192_Disk_30_flavor"
      keypair: "{{ guid }}-keypair"
      security_group: "{{ guid }}-HostSG"
      internal_network: "{{ guid }}-dev-network"


