---
- name: print control hostname
- hosts: localhost
  connection: local
  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address
  
- name: Play to setup infrastructure on OpenStack 
  connection: local
  hosts: localhost

  roles:
    - role: create-instances
      vars:
        guid: "{{ lookup('ENV','GUID') }}"
