---
- name: Create infrastructure for multi-tier application (MTA) in OpenStack
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    guid: 3365
    deployment_name: "MTA"
    instance_settings:
      image: rhel-8.3
      flavor: "GLOBAL-CPU_4_Memory_8192_Disk_30_flavor"
      keypair: "{{ guid }}-keypair"
      security_group: "{{ guid }}-HostSG"
      internal_network: "{{ guid }}-dev-network"

  roles:
    - role: create-instance-role
      vars:
        instances:
          - name: frontend1
            group: load_balancers
          - name: app1
            group: app_servers
          - name: app2
            group: app_servers
          - name: appdb1
            group: database_servers

