---
- name: Create infrastructure for multi-tier application in OpenStack
  hosts: localhost
  connection: local

  vars:
    guid: 3365
    multitierinfra:
      image: rhel-8.3
      flavor: "GLOBAL-CPU_4_Memory_8192_Disk_30_flavor"
      keypair: "{{ guid }}-keypair"
      security_group: "{{ guid }}-HostSG"
      internal_network: "{{ guid }}-dev-network"
      AnsibleGroup: mitzicom_multitier_app_servers

  roles:
    - role: create-instance
      vars:
        instances:
          - name: frontend1
            metadata:
              deployment_name: frontend
          - name: app1
            metadata:
              deployment_name: app1
          - name: app2
            metadata:
              deployment_name: app2
          - name: appdb1
            metadata:
              deployment_name: appdb1

    - role: build-in-memory-inventory
        

#    - role: configure-instance


