---
- name: Create infrastructure for multi-tier application in OpenStack
  hosts: localhost
  connection: local

  roles:
    - role: create-instance
      vars:
        instances:
          - name: frontend1
            metadata:
              AnsibleGroup: osp_instances_lab
              deployment_name: dev
  vars:
    guid: 3365
    multitierinfra:
      image: rhel-8.3
      flavor: "GLOBAL-CPU_4_Memory_8192_Disk_30_flavor"
      keypair: "{{ guid }}-keypair"
      security_group: "{{ guid }}-HostSG"
      internal_network: "{{ guid }}-dev-network"

