---
- name: Play to setup infrastructure on OpenStack 
  hosts: control-node 

  roles:
    - role: create-instances
      vars:
        guid: "{{ lookup('ENV','GUID') }}"
  ansible.builtin.debug:
    msg: System {{ inventory_hostname }} 
