- import_playbook: build-in-memory-inventory.yml

- name: End to end smoke tests
  hosts: load_balancers
  become: no
  gather_facts: no
  tags:
    - smoketest  

  vars:
    appservers:
      - name: app1
      - name: app2

  tasks:

    - name: Check app server for correct response from load-balancers
      uri:
        url: "http://{{ item.name }}:8080/ping"
        return_content: yes
      retries: 3
      delay: 1
      with_items:
        -  "{{ appservers }}"

    - name: Check app server for response through load balancers
      uri:
        url: "http://localhost/ping"
        return_content: yes
      retries: 3
      delay: 1

