- import_playbook: build-in-memory-inventory.yml

- name: End to end smoke tests
  hosts: frontend1
  become: no
  gather_facts: no
  tags:
    - smoketest  

  vars:
    appservers:
      - name: app1
      - name: app2

  tasks:
    - name: Check app server for correct response from load-balancers
      uri:
        url: "http://{{ appserver.name }}:8080/ping"
        return_content: yes
      until: '"alive" in result.content'
      retries: 3
      delay: 1
      register: result
      loop: "{{ appservers }}"
      loop_control:
        loop_var: appserver
