---
- name: Collect instance info
  os_server_info:
  register: os_instances

- name: print host list
  debug: var=os_instances

- name: Build in-Memory inventory
  add_host:
    host: "{{ os_instance.name }}"
    group: "{{ os_instance.metadata.AnsibleGroup}}"
  #when: os_instance.metadata.DeployName ==  instance_settings.deployment_name
  loop: "{{ os_instances.openstack_servers }}"
  loop_control:
    loop_var: os_instance

- name: Print current hosts
  debug: var=groups
