---
- name: Collect instance info
  os_server_info:
  register: instances

- name: print host list
  debug: var=instances

- name: Build in-Memory inventory
  add_host:
    host: "{{ instance.name }}"
    group: "{{ instance.metadata.AnsibleGroup}}"
    ansible_host: "{{ instance.private_v4 }}"
  when: instance.metadata.deployment_name is defined and instance.metadata.deployment_name == deployment_name
  loop: "{{ instances.openstack_servers }}"
  loop_control:
    loop_var: instance

- name: Print current hosts
  debug: var=groups
