---
- name: Create Instance
  openstack.cloud.server:
    name: "{{ instance.name }}"
    image: "{{ multitierinfra.image }}"
    key_name: "{{ multitierinfra.keypair }}"
    flavor: "{{ multitierinfra.flavor }}"
    security_groups: "{{ multitierinfra.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: "{{ multitierinfra.internal_network }}"
    meta: "AnsibleGroup={{instance.metadata.AnsibleGroup}},deployment_name={{instance.metadata.deployment_name}}"
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance
