---
- name: Create Instance
  openstack.cloud.server:
    name: "{{ instance.name }}"
    image: "{{ instance.image }}"
    #key_name: "{{ instance.keypair }}"
    flavor: "{{ instance.flavor }}"
    security_groups: "{{ instance.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: "{{ instance.internal_network }}"
    meta: "AnsibleGroup={{metadata.AnsibleGroup}},deployment_name={{metadata.deployment_name}}"
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance
