---
- name: Gather network facts
  setup:
    gather_subset:
      - 'network'
  delegate_facts: true
  delegate_to: localhost
  connection: local

- name: Update DNS IP
  become: yes
  lineinfile:
    state: present
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "{{ item }}"
  loop:
    - PEERDNS=no
    - DNS1="{{DNSaddress}}"
  register: network_update

- name: restart network manager
  become: yes
  service:
    name: NetworkManager
    state: restarted
  when: network_update.changed | bool

- name: install katello-ca-consumer package
  become: yes
  yum:
    name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
    disable_gpg_check: true

- name: register system and attach subs
  become: yes
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_activationkey }}"
    org_id: "{{ satellite_org }}"
    auto_attach: true

- name: Install firewalld
  become: yes
  yum:
    name: firewalld
    state: latest
