---
# tasks file for deploy-postgress-role
#
#
- name: Set timezone to Australia/Sydney
  community.general.timezone:
    name: Australia/Sydney

- name: Disable stream for postgreslq
  command: dnf -qy module disable postgresql
  args:
    warn: false
    
- name: Copy supporting packages (non-Satellite) for local installation
  copy:
    src: "{{ role_path }}/files/libicu-60.3-2.el8_1.x86_64.rpm"
    dest: /tmp
    mode: 0644

- name: Install libicu dependency
  # unfortunately the satellite server has a circular link to this file, but the file itself
  # is not available. We can download from the web, or take advantage from the role 'files'
  command: dnf -qy install "/tmp/libicu-60.3-2.el8_1.x86_64.rpm"
  args:
    warn: false

- name: Install Postgres packages
  package:
    name: "{{ __package }}"
    state: present
    disable_gpg_check: True
  loop:
    - "{{ postgres_rhel8_repo }}"
    - "{{ postgres_packages }}"
    - "{{ postgres_library }}"
  loop_control:
    loop_var: __package

- name: Check if Postgres initialized
  stat:
    path: "{{ postgres_data_dir }}/PG_VERSION"
  register: r_postgres_init_dir_state

- when: not r_postgres_init_dir_state.stat.exists
  name: Run Postgres initdb to initialize if postgres not initialized
  command: "{{ postgres_bin_path }}/postgresql-12-setup initdb"
  notify: restart_postgres

- name: Setup Postgres for remote password auth
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_data_dir }}/pg_hba.conf"
  notify: restart_postgres

- name: Setup Postgres to listen on network interfaces
  lineinfile:
    dest: "{{ postgres_data_dir }}/postgresql.conf"
    line: "listen_addresses = '*'"
    insertafter: "#listen_addresses"
  notify: restart_postgres

- name: Setup Postgres as started and enabled on boot.
  service:
    name: "{{ postgres_service }}"
    state: "{{ postgres_service_state | default('started') }}"
    enabled: "{{ postgres_service_enabled | default(true) }}"

- name: Configure Postgres resources, user, database etc
  become_user: "{{ postgres_user }}"
  block:

    - name: Setup Postgres database(s)
      postgresql_db:
        name: "{{ __database.name }}"
        state: "{{ __database.state | default('present') }}"
      loop: "{{ postgres_databases }}"
      loop_control:
        loop_var: __database

    - name: Create Postgres user(s)
      postgresql_user:
        name: "{{ __user.name }}"
        password: "{{ __user.password | default(omit) }}"
        encrypted: true # "{{ __user.encrypted | default(omit) }}"
        priv: "{{ __user.priv | default(omit) }}"
        db: "{{ __user.database | default(omit) }}"
        # role_attr_flags: "{{ __user.role_attr_flags | default(omit) }}"
        state: "{{ __user.state | default('present') }}"
      loop: "{{ postgres_users }}"
      loop_control:
        loop_var: __user
      no_log: "{{ postgres_user_no_log_state | default(false) }}"




