---
- name: Create new OpenStack virtual instance
  openstack.cloud.server:
    name: "{{ instance.name }}"
    image: "{{ instance_settings.image }}"
    key_name: "{{ instance_settings.keypair }}"
    flavor: "{{ instance_settings.flavor }}"
    security_groups: "{{ instance_settings.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: "{{ instance_settings.internal_network }}"
    meta: "AnsibleGroup={{instance.group}},deployment_name={{deployment_name}}"
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance

